List<Map<String, String>> listData = [
  {
    "title": "Tuân thủ uống thuốc",
    "imageUrl": "assets/img3D/thuoc.png",
    "result": "Bình Thường", //
    "dateTime": "11 th01  12:34", //
    "data": "123", //
    "unit": "%",
    "average": "Trung bình trong 30 ngày",
    "dataAverage": "120", //
  },
  {
    "title": "Huyết Áp",
    "imageUrl": "assets/img3D/huyetap.png",
    "result": "Cao",
    "dateTime": "11 th02  1:34",
    "data": "110/90",
    "unit": "BPM",
    "average": "Trung bình trong 30 ngày",
    "dataAverage": "112/87",
  },
  {
    "title": "Nhịp tim",
    "imageUrl": "assets/img3D/nhiptim.png",
    "result": "Rất Cao",
    "dateTime": "11 th04  12:34",
    "data": "129",
    "unit": "BMP",
    "average": "Trung bình trong 30 ngày",
    "dataAverage": "119",
  },
  {
    "title": "Cân nặng",
    "imageUrl": "assets/img3D/cannang.png",
    "result": "Thấp",
    "dateTime": "1 th02  2:44",
    "data": "45",
    "unit": "kg",
    "average": "So với lần đo trước",
    "dataAverage": "+2",
  },
  {
    "title": "Chiều cao",
    "imageUrl": "assets/img3D/chieucao.png",
    "result": "Bình Thường",
    "dateTime": "19 th08  4:04",
    "data": "170",
    "unit": "cm",
    "average": "So với lần đo trước",
    "dataAverage": "-4",
  },
  {
    "title": "Đường huyết",
    "imageUrl": "assets/img3D/treatment_medical/tieuduong.png",
    "result": "Bình Thường",
    "dateTime": "19 th08  4:04",
    "data": "123",
    "unit": "mmol/L",
    "average": "So với lần đo trước",
    "dataAverage": "-23%",
  },
  {
    "title": "Chức năng thận",
    "imageUrl": "assets/img3D/treatment_medical/than.png",
    "result": "Bình Thường",
    "dateTime": "20 th3  4:04",
    "data": "193.6",
    "unit": "mL/phút/1.73m2",
    "average": "So với lần đo trước",
    "dataAverage": "-30%",
  },
  {
    "title": "Mỡ máu",
    "imageUrl": "assets/img3D/treatment_medical/momau.webp",
    "result": "Bình Thường",
    "dateTime": "19 th08  4:04",
    "data": "189",
    "unit": "mmol/L",
    "average": "So với lần đo trước",
    "dataAverage": "+20%",
  },
  {
    "title": "Men gan",
    "imageUrl": "assets/img3D/treatment_medical/gan.png",
    "result": "Bình Thường",
    "dateTime": "19 th08  4:04",
    "data": "---",
    "unit": "UI/L",
    "average": "So với lần đo trước",
    "dataAverage": "---",
  },
];
